% Specifications that define WebIDL content (W3C perspective)
% Reffy
% August 12, 2017

113 specifications were crawled in this report.


## Specifications that could not be rendered

Reffy could not fetch or render these specifications for some reason. This may happen when a network error occurred or when a specification uses an old version of ReSpec.

- [2dcontext](https://www.w3.org/TR/2dcontext): `FetchError: request to https://api.w3.org/specifications/2dcontext failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/2dcontext failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [accelerometer](https://www.w3.org/TR/accelerometer): `FetchError: request to https://api.w3.org/specifications/accelerometer failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/accelerometer failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [ambient-light](https://www.w3.org/TR/ambient-light): `FetchError: request to https://api.w3.org/specifications/ambient-light failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/ambient-light failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [appmanifest](https://www.w3.org/TR/appmanifest): `FetchError: request to https://api.w3.org/specifications/appmanifest failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/appmanifest failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [audio-output](https://www.w3.org/TR/audio-output): `FetchError: request to https://api.w3.org/specifications/audio-output failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/audio-output failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [battery-status](https://www.w3.org/TR/battery-status): `FetchError: request to https://api.w3.org/specifications/battery-status failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/battery-status failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [beacon](https://www.w3.org/TR/beacon): `FetchError: request to https://api.w3.org/specifications/beacon failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/beacon failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [clipboard-apis](https://www.w3.org/TR/clipboard-apis): `FetchError: request to https://api.w3.org/specifications/clipboard-apis failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/clipboard-apis failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [compositing-1](https://www.w3.org/TR/compositing-1): `FetchError: request to https://api.w3.org/specifications/compositing-1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/compositing-1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [credential-management-1](https://www.w3.org/TR/credential-management-1): `FetchError: request to https://api.w3.org/specifications/credential-management-1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/credential-management-1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [CSP3](https://www.w3.org/TR/CSP3): `FetchError: request to https://api.w3.org/specifications/CSP3 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/CSP3 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [css-font-loading-3](https://www.w3.org/TR/css-font-loading-3): `FetchError: request to https://api.w3.org/specifications/css-font-loading-3 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/css-font-loading-3 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [css-fonts-3](https://www.w3.org/TR/css-fonts-3): `FetchError: request to https://api.w3.org/specifications/css-fonts-3 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/css-fonts-3 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [css-paint-api-1](https://www.w3.org/TR/css-paint-api-1): `FetchError: request to https://api.w3.org/specifications/css-paint-api-1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/css-paint-api-1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [css-properties-values-api-1](https://www.w3.org/TR/css-properties-values-api-1): `FetchError: request to https://api.w3.org/specifications/css-properties-values-api-1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/css-properties-values-api-1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [css-pseudo-4](https://www.w3.org/TR/css-pseudo-4): `FetchError: request to https://api.w3.org/specifications/css-pseudo-4 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/css-pseudo-4 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [css-syntax-3](https://www.w3.org/TR/css-syntax-3): `FetchError: request to https://api.w3.org/specifications/css-syntax-3 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/css-syntax-3 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [css-typed-om-1](https://www.w3.org/TR/css-typed-om-1): `FetchError: request to https://api.w3.org/specifications/css-typed-om-1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/css-typed-om-1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [css-values-3](https://www.w3.org/TR/css-values-3): `FetchError: request to https://api.w3.org/specifications/css-values-3 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/css-values-3 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [css-writing-modes-3](https://www.w3.org/TR/css-writing-modes-3): `FetchError: request to https://api.w3.org/specifications/css-writing-modes-3 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/css-writing-modes-3 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [css3-selectors](https://www.w3.org/TR/css3-selectors): `FetchError: request to https://api.w3.org/specifications/css3-selectors failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/css3-selectors failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [cssom-1](https://www.w3.org/TR/cssom-1): `FetchError: request to https://api.w3.org/specifications/cssom-1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/cssom-1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [cssom-view-1](https://www.w3.org/TR/cssom-view-1): `FetchError: request to https://api.w3.org/specifications/cssom-view-1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/cssom-view-1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [custom-elements](https://www.w3.org/TR/custom-elements): `FetchError: request to https://api.w3.org/specifications/custom-elements failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/custom-elements failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [DOM-Parsing](https://www.w3.org/TR/DOM-Parsing): `FetchError: request to https://api.w3.org/specifications/DOM-Parsing failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/DOM-Parsing failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [dom41](https://www.w3.org/TR/dom41): `FetchError: request to https://api.w3.org/specifications/dom41 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/dom41 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [ElementTraversal](https://www.w3.org/TR/ElementTraversal): `FetchError: request to https://api.w3.org/specifications/ElementTraversal failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/ElementTraversal failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [encoding](https://www.w3.org/TR/encoding): `FetchError: request to https://api.w3.org/specifications/encoding failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/encoding failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [encrypted-media](https://www.w3.org/TR/encrypted-media): `FetchError: request to https://api.w3.org/specifications/encrypted-media failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/encrypted-media failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [eventsource](https://www.w3.org/TR/eventsource): `FetchError: request to https://api.w3.org/specifications/eventsource failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/eventsource failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [FileAPI](https://www.w3.org/TR/FileAPI): `FetchError: request to https://api.w3.org/specifications/FileAPI failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/FileAPI failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [gamepad](https://www.w3.org/TR/gamepad): `FetchError: request to https://api.w3.org/specifications/gamepad failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/gamepad failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [generic-sensor](https://www.w3.org/TR/generic-sensor): `FetchError: request to https://api.w3.org/specifications/generic-sensor failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/generic-sensor failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [geolocation-API](https://www.w3.org/TR/geolocation-API): `FetchError: request to https://api.w3.org/specifications/geolocation-API failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/geolocation-API failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [geometry-1](https://www.w3.org/TR/geometry-1): `FetchError: request to https://api.w3.org/specifications/geometry-1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/geometry-1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [gyroscope](https://www.w3.org/TR/gyroscope): `FetchError: request to https://api.w3.org/specifications/gyroscope failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/gyroscope failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [hr-time-3](https://www.w3.org/TR/hr-time-3): `FetchError: request to https://api.w3.org/specifications/hr-time-3 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/hr-time-3 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [html-media-capture](https://www.w3.org/TR/html-media-capture): `FetchError: request to https://api.w3.org/specifications/html-media-capture failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/html-media-capture failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [html52](https://www.w3.org/TR/html52): `FetchError: request to https://api.w3.org/specifications/html52 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/html52 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [https://console.spec.whatwg.org/](https://console.spec.whatwg.org/): `FetchError: request to https://console.spec.whatwg.org/ failed, reason: getaddrinfo ENOTFOUND console.spec.whatwg.org console.spec.whatwg.org:443 FetchError: request to https://console.spec.whatwg.org/ failed, reason: getaddrinfo ENOTFOUND console.spec.whatwg.org console.spec.whatwg.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [https://fetch.spec.whatwg.org/](https://fetch.spec.whatwg.org/): `FetchError: request to https://fetch.spec.whatwg.org/ failed, reason: getaddrinfo ENOTFOUND fetch.spec.whatwg.org fetch.spec.whatwg.org:443 FetchError: request to https://fetch.spec.whatwg.org/ failed, reason: getaddrinfo ENOTFOUND fetch.spec.whatwg.org fetch.spec.whatwg.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [https://fullscreen.spec.whatwg.org/](https://fullscreen.spec.whatwg.org/): `FetchError: request to https://fullscreen.spec.whatwg.org/ failed, reason: getaddrinfo ENOTFOUND fullscreen.spec.whatwg.org fullscreen.spec.whatwg.org:443 FetchError: request to https://fullscreen.spec.whatwg.org/ failed, reason: getaddrinfo ENOTFOUND fullscreen.spec.whatwg.org fullscreen.spec.whatwg.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [https://storage.spec.whatwg.org/](https://storage.spec.whatwg.org/): `FetchError: request to https://storage.spec.whatwg.org/ failed, reason: getaddrinfo ENOTFOUND storage.spec.whatwg.org storage.spec.whatwg.org:443 FetchError: request to https://storage.spec.whatwg.org/ failed, reason: getaddrinfo ENOTFOUND storage.spec.whatwg.org storage.spec.whatwg.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [https://streams.spec.whatwg.org/](https://streams.spec.whatwg.org/): `FetchError: request to https://streams.spec.whatwg.org/ failed, reason: getaddrinfo ENOTFOUND streams.spec.whatwg.org streams.spec.whatwg.org:443 FetchError: request to https://streams.spec.whatwg.org/ failed, reason: getaddrinfo ENOTFOUND streams.spec.whatwg.org streams.spec.whatwg.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [https://url.spec.whatwg.org/](https://url.spec.whatwg.org/): `FetchError: request to https://url.spec.whatwg.org/ failed, reason: getaddrinfo ENOTFOUND url.spec.whatwg.org url.spec.whatwg.org:443 FetchError: request to https://url.spec.whatwg.org/ failed, reason: getaddrinfo ENOTFOUND url.spec.whatwg.org url.spec.whatwg.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [https://www.khronos.org/registry/webgl/specs/latest/1.0/](https://www.khronos.org/registry/webgl/specs/latest/1.0/): `FetchError: request to https://www.khronos.org/registry/webgl/specs/latest/1.0/ failed, reason: getaddrinfo ENOTFOUND www.khronos.org www.khronos.org:443 FetchError: request to https://www.khronos.org/registry/webgl/specs/latest/1.0/ failed, reason: getaddrinfo ENOTFOUND www.khronos.org www.khronos.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [https://www.khronos.org/registry/webgl/specs/latest/2.0/](https://www.khronos.org/registry/webgl/specs/latest/2.0/): `FetchError: request to https://www.khronos.org/registry/webgl/specs/latest/2.0/ failed, reason: getaddrinfo ENOTFOUND www.khronos.org www.khronos.org:443 FetchError: request to https://www.khronos.org/registry/webgl/specs/latest/2.0/ failed, reason: getaddrinfo ENOTFOUND www.khronos.org www.khronos.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [https://xhr.spec.whatwg.org/](https://xhr.spec.whatwg.org/): `FetchError: request to https://xhr.spec.whatwg.org/ failed, reason: getaddrinfo ENOTFOUND xhr.spec.whatwg.org xhr.spec.whatwg.org:443 FetchError: request to https://xhr.spec.whatwg.org/ failed, reason: getaddrinfo ENOTFOUND xhr.spec.whatwg.org xhr.spec.whatwg.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [image-capture](https://www.w3.org/TR/image-capture): `FetchError: request to https://api.w3.org/specifications/image-capture failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/image-capture failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [IndexedDB-2](https://www.w3.org/TR/IndexedDB-2): `FetchError: request to https://api.w3.org/specifications/IndexedDB-2 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/IndexedDB-2 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [input-events-2](https://www.w3.org/TR/input-events-2): `FetchError: request to https://api.w3.org/specifications/input-events-2 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/input-events-2 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [magnetometer](https://www.w3.org/TR/magnetometer): `FetchError: request to https://api.w3.org/specifications/magnetometer failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/magnetometer failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [media-source](https://www.w3.org/TR/media-source): `FetchError: request to https://api.w3.org/specifications/media-source failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/media-source failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [mediacapture-depth](https://www.w3.org/TR/mediacapture-depth): `FetchError: request to https://api.w3.org/specifications/mediacapture-depth failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/mediacapture-depth failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [mediacapture-fromelement](https://www.w3.org/TR/mediacapture-fromelement): `FetchError: request to https://api.w3.org/specifications/mediacapture-fromelement failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/mediacapture-fromelement failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [mediacapture-streams](https://www.w3.org/TR/mediacapture-streams): `FetchError: request to https://api.w3.org/specifications/mediacapture-streams failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/mediacapture-streams failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [mediaont-api-1.0](https://www.w3.org/TR/mediaont-api-1.0): `FetchError: request to https://api.w3.org/specifications/mediaont-api-1.0 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/mediaont-api-1.0 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [mediastream-recording](https://www.w3.org/TR/mediastream-recording): `FetchError: request to https://api.w3.org/specifications/mediastream-recording failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/mediastream-recording failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [mixed-content](https://www.w3.org/TR/mixed-content): `FetchError: request to https://api.w3.org/specifications/mixed-content failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/mixed-content failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [navigation-timing-2](https://www.w3.org/TR/navigation-timing-2): `FetchError: request to https://api.w3.org/specifications/navigation-timing-2 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/navigation-timing-2 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [notifications](https://www.w3.org/TR/notifications): `FetchError: request to https://api.w3.org/specifications/notifications failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/notifications failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [orientation-event](https://www.w3.org/TR/orientation-event): `FetchError: request to https://api.w3.org/specifications/orientation-event failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/orientation-event failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [orientation-sensor](https://www.w3.org/TR/orientation-sensor): `FetchError: request to https://api.w3.org/specifications/orientation-sensor failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/orientation-sensor failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [page-visibility-2](https://www.w3.org/TR/page-visibility-2): `FetchError: request to https://api.w3.org/specifications/page-visibility-2 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/page-visibility-2 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [payment-handler](https://www.w3.org/TR/payment-handler): `FetchError: request to https://api.w3.org/specifications/payment-handler failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/payment-handler failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [payment-method-basic-card](https://www.w3.org/TR/payment-method-basic-card): `FetchError: request to https://api.w3.org/specifications/payment-method-basic-card failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/payment-method-basic-card failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [payment-request](https://www.w3.org/TR/payment-request): `FetchError: request to https://api.w3.org/specifications/payment-request failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/payment-request failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [performance-timeline-2](https://www.w3.org/TR/performance-timeline-2): `FetchError: request to https://api.w3.org/specifications/performance-timeline-2 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/performance-timeline-2 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [permissions](https://www.w3.org/TR/permissions): `FetchError: request to https://api.w3.org/specifications/permissions failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/permissions failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [pointerevents2](https://www.w3.org/TR/pointerevents2): `FetchError: request to https://api.w3.org/specifications/pointerevents2 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/pointerevents2 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [pointerlock-2](https://www.w3.org/TR/pointerlock-2): `FetchError: request to https://api.w3.org/specifications/pointerlock-2 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/pointerlock-2 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [preload](https://www.w3.org/TR/preload): `FetchError: request to https://api.w3.org/specifications/preload failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/preload failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [presentation-api](https://www.w3.org/TR/presentation-api): `FetchError: request to https://api.w3.org/specifications/presentation-api failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/presentation-api failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [progress-events](https://www.w3.org/TR/progress-events): `FetchError: request to https://api.w3.org/specifications/progress-events failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/progress-events failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [proximity](https://www.w3.org/TR/proximity): `FetchError: request to https://api.w3.org/specifications/proximity failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/proximity failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [push-api](https://www.w3.org/TR/push-api): `FetchError: request to https://api.w3.org/specifications/push-api failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/push-api failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [referrer-policy](https://www.w3.org/TR/referrer-policy): `FetchError: request to https://api.w3.org/specifications/referrer-policy failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/referrer-policy failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [remote-playback](https://www.w3.org/TR/remote-playback): `FetchError: request to https://api.w3.org/specifications/remote-playback failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/remote-playback failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [requestidlecallback](https://www.w3.org/TR/requestidlecallback): `FetchError: request to https://api.w3.org/specifications/requestidlecallback failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/requestidlecallback failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [resource-timing-2](https://www.w3.org/TR/resource-timing-2): `FetchError: request to https://api.w3.org/specifications/resource-timing-2 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/resource-timing-2 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [screen-capture](https://www.w3.org/TR/screen-capture): `FetchError: request to https://api.w3.org/specifications/screen-capture failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/screen-capture failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [screen-orientation](https://www.w3.org/TR/screen-orientation): `FetchError: request to https://api.w3.org/specifications/screen-orientation failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/screen-orientation failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [secure-contexts](https://www.w3.org/TR/secure-contexts): `FetchError: request to https://api.w3.org/specifications/secure-contexts failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/secure-contexts failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [selection-api](https://www.w3.org/TR/selection-api): `FetchError: request to https://api.w3.org/specifications/selection-api failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/selection-api failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [selectors-api](https://www.w3.org/TR/selectors-api): `FetchError: request to https://api.w3.org/specifications/selectors-api failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/selectors-api failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [service-workers-1](https://www.w3.org/TR/service-workers-1): `FetchError: request to https://api.w3.org/specifications/service-workers-1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/service-workers-1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [shadow-dom](https://www.w3.org/TR/shadow-dom): `FetchError: request to https://api.w3.org/specifications/shadow-dom failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/shadow-dom failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [SVG2](https://www.w3.org/TR/SVG2): `FetchError: request to https://api.w3.org/specifications/SVG2 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/SVG2 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [touch-events](https://www.w3.org/TR/touch-events): `FetchError: request to https://api.w3.org/specifications/touch-events failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/touch-events failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [uievents](https://www.w3.org/TR/uievents): `FetchError: request to https://api.w3.org/specifications/uievents failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/uievents failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [uievents-code](https://www.w3.org/TR/uievents-code): `FetchError: request to https://api.w3.org/specifications/uievents-code failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/uievents-code failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [uievents-key](https://www.w3.org/TR/uievents-key): `FetchError: request to https://api.w3.org/specifications/uievents-key failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/uievents-key failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [UISecurity](https://www.w3.org/TR/UISecurity): `FetchError: request to https://api.w3.org/specifications/UISecurity failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/UISecurity failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [user-timing-2](https://www.w3.org/TR/user-timing-2): `FetchError: request to https://api.w3.org/specifications/user-timing-2 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/user-timing-2 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [vibration](https://www.w3.org/TR/vibration): `FetchError: request to https://api.w3.org/specifications/vibration failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/vibration failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [wake-lock](https://www.w3.org/TR/wake-lock): `FetchError: request to https://api.w3.org/specifications/wake-lock failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/wake-lock failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [web-animations-1](https://www.w3.org/TR/web-animations-1): `FetchError: request to https://api.w3.org/specifications/web-animations-1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/web-animations-1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [webaudio](https://www.w3.org/TR/webaudio): `FetchError: request to https://api.w3.org/specifications/webaudio failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/webaudio failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [webauthn](https://www.w3.org/TR/webauthn): `FetchError: request to https://api.w3.org/specifications/webauthn failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/webauthn failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [WebCryptoAPI](https://www.w3.org/TR/WebCryptoAPI): `FetchError: request to https://api.w3.org/specifications/WebCryptoAPI failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/WebCryptoAPI failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [webdriver](https://www.w3.org/TR/webdriver): `FetchError: request to https://api.w3.org/specifications/webdriver failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/webdriver failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [WebIDL-1](https://www.w3.org/TR/WebIDL-1): `FetchError: request to https://api.w3.org/specifications/WebIDL-1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/WebIDL-1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [webmessaging](https://www.w3.org/TR/webmessaging): `FetchError: request to https://api.w3.org/specifications/webmessaging failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/webmessaging failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [webrtc](https://www.w3.org/TR/webrtc): `FetchError: request to https://api.w3.org/specifications/webrtc failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/webrtc failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [webrtc-stats](https://www.w3.org/TR/webrtc-stats): `FetchError: request to https://api.w3.org/specifications/webrtc-stats failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/webrtc-stats failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [websockets](https://www.w3.org/TR/websockets): `FetchError: request to https://api.w3.org/specifications/websockets failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/websockets failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [webstorage](https://www.w3.org/TR/webstorage): `FetchError: request to https://api.w3.org/specifications/webstorage failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/webstorage failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [webvtt1](https://www.w3.org/TR/webvtt1): `FetchError: request to https://api.w3.org/specifications/webvtt1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/webvtt1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [workers](https://www.w3.org/TR/workers): `FetchError: request to https://api.w3.org/specifications/workers failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/workers failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
- [worklets-1](https://www.w3.org/TR/worklets-1): `FetchError: request to https://api.w3.org/specifications/worklets-1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443 FetchError: request to https://api.w3.org/specifications/worklets-1 failed, reason: getaddrinfo ENOTFOUND api.w3.org api.w3.org:443
    at ClientRequest.<anonymous> (/home/dom/github.com/reffy/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`

=> 110 specifications found


## Specifications without normative dependencies


=> 0 specification found


## Specifications without WebIDL definitions

- [ContentEditable](https://w3c.github.io/editing/contentEditable.html)

=> 1 specification found

Not all specifications define IDL content, presence in this list may be completely normal. Reffy's current focus is on IDL specifications, the number of specifications listed here should remain minimal.


## List of specifications with invalid WebIDL content


=> 0 specification found


## List of specifications with obsolete WebIDL constructs


=> 0 specification found


## Specifications that use WebIDL but do not reference the WebIDL spec

- [Static Range](https://w3c.github.io/staticrange/)

=> 1 specification found



## List of WebIDL names not defined in the specifications crawled

- `Navigator` used in [Media Session Standard](https://wicg.github.io/mediasession/)
- `Node` used in [Static Range](https://w3c.github.io/staticrange/)
- `Window` used in [Media Session Standard](https://wicg.github.io/mediasession/)

=> 3 WebIDL names found

Some of them may be type errors in specs (e.g. "int" does not exist, "Array" cannot be used on its own, etc.)
Also, please keep in mind that Reffy only knows about IDL terms defined in the specifications that were crawled **and** that do not have invalid IDL content.


## List of WebIDL names defined in more than one spec


=> 0 WebIDL name found


## Missing references for WebIDL names


=> 0 missing reference for IDL definitions found in 0 specification


## Missing references based on document links


=> 0 missing reference for links found in 0 specification


## Reference URL is inconsistent with URL used in document links


=> 0 inconsistent reference for links found in 0 specification
